[serviceakasar]
name = "multiprocess"
binary = "./multiprocess"
#rollout = "5m"
env = ["env=alpha"]
LogLevel = "debug"
colocate = [
    [
        "github.com/kanengo/akasar/examples/multiprocess/components/User",
        "github.com/kanengo/akasar/examples/multiprocess/components/Store",
    ],
    [
        "github.com/kanengo/akasar/examples/multiprocess/components/VIP",

    ]
]


